In [1]:
# pip install imbalanced-learn

In [2]:
import numpy as np
%pip install pandas
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
data = pd.read_csv("Datasets\\Fertilizer Prediction.csv")
data = data.drop(columns = ["Crop Type","Soil Type"], axis = 1)
data.head()

temperature  Humidity  moisture   N  K   P Fertilizer Name
0           26        52        38  37  0   0            Urea
1           29        52        45  12  0  36             DAP
2           34        65        62   7  9  30        14-35-14
3           32        62        34  22  0  20           28-28
4           28        54        46  35  0   0            Urea

In [4]:
data.columns

Index(['temperature', 'Humidity', 'moisture', 'N', 'K', 'P',
       'Fertilizer Name'],
      dtype='object')

In [5]:
features = ['N', 'K', 'P', 'temperature', 'moisture','Humidity']

X = data[features]
X.head()

N  K   P  temperature  moisture  Humidity
0  37  0   0           26        38        52
1  12  0  36           29        45        52
2   7  9  30           34        62        65
3  22  0  20           32        34        62
4  35  0   0           28        46        54

In [6]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[ 1.56753938, -0.58491041, -1.38760694, -1.22908361, -0.46206429,
        -1.2307368 ],
       [-0.59865825, -0.58491041,  1.29720909, -0.36814533,  0.16212782,
        -1.2307368 ],
       [-1.03189778,  0.97077668,  0.84973976,  1.06675181,  1.67802295,
         1.00649239],
       [ 0.2678208 , -0.58491041,  0.10395752,  0.49279296, -0.8187455 ,
         0.49020873],
       [ 1.39424356, -0.58491041, -1.38760694, -0.65512475,  0.25129812,
        -0.8865477 ],
       [-0.59865825,  1.1436308 , -0.41809004, -1.22908361, -0.7295752 ,
        -1.2307368 ],
       [-0.85860197, -0.58491041, -0.64182471, -1.51606304,  1.85636356,
        -1.57492591],
       [ 1.914131  , -0.58491041, -1.38760694,  0.77977239,  0.60797933,
         0.83439783],
       [ 0.18117289, -0.58491041, -0.04519892, -0.0811659 , -0.10538308,
         0.14601962],
       [-0.85860197,  0.62506844,  0.84973976, -0.36814533, -0.9079158 ,
        -0.19816949],
       [-0.51201035, -0.58491041,  1.59552199, -0.

In [7]:
pca = PCA(n_components = len(features))
X_pca = pca.fit_transform(X_scaled)
X_pca

array([[-2.73212430e+00,  6.45617351e-01, -8.98985248e-02,
         2.00901899e-01,  1.82176342e-01, -2.56793679e-02],
       [-1.88977803e-01, -1.20169350e+00, -2.19684079e-01,
        -1.45892650e+00,  2.41118224e-01,  5.87492401e-01],
       [ 2.30269988e+00, -4.67967486e-01,  1.46576457e+00,
         5.31741681e-02,  1.43511554e-01,  5.21180190e-02],
       [ 2.77551151e-01,  7.78701437e-01, -9.32708759e-01,
        -1.38923210e-01, -7.40068085e-02, -4.01918050e-03],
       [-2.06748979e+00,  9.29664251e-01,  5.56493417e-01,
         1.19685610e-01,  7.76889755e-02,  1.44774076e-01],
       [-1.19582773e+00, -1.72374279e+00, -3.26914207e-01,
         9.25108802e-01, -1.83025920e-01,  3.50870157e-02],
       [-1.54086266e+00, -1.26838762e+00,  1.92610571e+00,
        -1.08992783e+00, -9.08655316e-01,  9.81612701e-02],
       [-4.69261520e-01,  2.53079289e+00,  7.96902345e-01,
         4.94332112e-01,  3.08281074e-01, -7.61603842e-02],
       [-1.73792622e-01,  4.06087758e-01, -1.853

In [8]:
explained_variance_ratio = pca.explained_variance_ratio_
explained_variance_ratio

array([0.36360754, 0.29071983, 0.16578289, 0.14557862, 0.03000049,
       0.00431064])

In [9]:
eigenvectors = pca.components_
eigenvectors

array([[-0.38376023,  0.18514493,  0.43147274,  0.55241298,  0.1246853 ,
         0.55818831],
       [ 0.57715763, -0.44574267, -0.35804151,  0.41893486,  0.00564756,
         0.40554964],
       [ 0.01216569,  0.16510537, -0.24865815, -0.03574452,  0.95314076,
        -0.031723  ],
       [ 0.07984572,  0.77673195, -0.53257126,  0.12591394, -0.26500666,
         0.14351707],
       [ 0.71439627,  0.36930439,  0.58188101, -0.00332771,  0.0754365 ,
        -0.09468365],
       [-0.05226648, -0.0087633 , -0.03986257,  0.70865395, -0.00501672,
        -0.70241498]])

In [10]:
weights = eigenvectors[0] * explained_variance_ratio[0]
for i in range(1, len(features)):
  weights += eigenvectors[i] * explained_variance_ratio[i]
weights

array([ 0.06310068,  0.08922261, -0.0486724 ,  0.33801366,  0.16865501,
        0.33062827])

In [11]:

weights /= weights.sum()
weights

array([ 0.06706077,  0.09482206, -0.05172699,  0.35922678,  0.17923949,
        0.3513779 ])

In [12]:
def calculate_sqi(X_scaled, weights):
  return (X_scaled * weights).sum(axis = 1)

In [13]:
sqi= calculate_sqi(X_scaled, weights)
sqi

array([-8.35358912e-01, -6.98351274e-01,  1.01652967e+00,  1.59641869e-01,
       -3.91995714e-01, -9.14820663e-01, -8.45112207e-01,  8.26955396e-01,
       -3.77125162e-02, -4.06877109e-01, -1.06492063e+00,  5.10542920e-01,
       -6.33664074e-01,  2.75427679e-01, -1.23905029e+00,  4.62786879e-01,
        5.53797946e-01, -1.20967444e+00, -6.50790726e-02, -2.17839389e-01,
       -3.49449025e-02,  1.05312814e+00,  6.86254011e-01, -5.30030590e-01,
        4.49868197e-01, -8.97965464e-01,  3.33277676e-01,  2.65835449e-01,
        9.95488269e-01, -1.05112030e+00, -2.95565844e-01, -4.14620726e-01,
        7.87100895e-01,  1.02053360e+00, -8.30176402e-01, -5.32942893e-01,
        3.04176292e-01,  1.06768705e+00, -1.19198838e+00, -4.97766848e-01,
       -9.28796873e-01,  2.14820269e-01,  1.44211042e-01,  1.11548065e+00,
        7.71534078e-01,  1.50461953e+00, -1.10738448e+00, -2.28328793e-01,
       -5.98372003e-02,  6.69393884e-01,  5.01238379e-01,  8.89693313e-01,
       -4.90805051e-01, -

In [14]:
minmax = MinMaxScaler()
sqi_scaled = minmax.fit_transform(sqi.reshape(-1, 1))
sqi_scaled

array([[0.14954228],
       [0.1932497 ],
       [0.74032147],
       [0.46696189],
       [0.29098154],
       [0.12419284],
       [0.14643084],
       [0.67984454],
       [0.40400299],
       [0.28623416],
       [0.07630878],
       [0.57890439],
       [0.21388585],
       [0.50389923],
       [0.02075891],
       [0.56366952],
       [0.59270337],
       [0.03013023],
       [0.39527267],
       [0.34653992],
       [0.4048859 ],
       [0.7519969 ],
       [0.63495876],
       [0.24694642],
       [0.55954828],
       [0.12956989],
       [0.52235422],
       [0.50083918],
       [0.73360895],
       [0.08071128],
       [0.32174406],
       [0.28376384],
       [0.66713037],
       [0.74159877],
       [0.15119558],
       [0.24601736],
       [0.51307046],
       [0.75664141],
       [0.03577233],
       [0.25723902],
       [0.11973422],
       [0.4845646 ],
       [0.46203923],
       [0.77188826],
       [0.66216434],
       [0.89602917],
       [0.0627622 ],
       [0.343

In [15]:
data['SQI'] = sqi_scaled
data.head()

temperature  Humidity  moisture   N  K   P Fertilizer Name       SQI
0           26        52        38  37  0   0            Urea  0.149542
1           29        52        45  12  0  36             DAP  0.193250
2           34        65        62   7  9  30        14-35-14  0.740321
3           32        62        34  22  0  20           28-28  0.466962
4           28        54        46  35  0   0            Urea  0.290982

In [16]:
print(min(data['SQI']))
print(max(data['SQI']))

0.0
1.0


In [17]:
fert_data = pd.read_csv('Datasets\\Fertilizer Prediction.csv')
fert_data = fert_data.drop(columns = ['Soil Type', 'Crop Type'])

In [18]:
# new_column_names = {
#     'Nitrogen': 'N',
#     'Potassium': 'K',
#     'Phosphorus': 'P',
    
# }

# fert_data.rename(columns = new_column_names, inplace = True)

# # fert_data = fert_data.reindex(columns = ['N', 'P', 'K', 'temperature', 'ph'])
# # print(fert_data.value_counts('Fertilizer'))

In [19]:
from imblearn.over_sampling import SMOTE
# from google.colab import files

X = fert_data.drop(columns = ['Fertilizer Name'], axis = 1)
y = fert_data['Fertilizer Name']

smote = SMOTE(random_state = 42)
X_resampled, y_resampled = smote.fit_resample(X, y)

df_resampled = pd.concat([pd.DataFrame(X_resampled, columns = X.columns), pd.Series(y_resampled, name = 'Fertilizer')], axis = 1)
print(df_resampled.head())
print(df_resampled.value_counts('Fertilizer'))
print(df_resampled)
# df_resampled.to_csv('New Crop Dataset.csv', index = False)
# files.download('New Crop Dataset.csv')

   temperature  Humidity  moisture   N  K   P Fertilizer
0           26        52        38  37  0   0       Urea
1           29        52        45  12  0  36        DAP
2           34        65        62   7  9  30   14-35-14
3           32        62        34  22  0  20      28-28
4           28        54        46  35  0   0       Urea
Fertilizer
10-26-26    22
14-35-14    22
17-17-17    22
20-20       22
28-28       22
DAP         22
Urea        22
Name: count, dtype: int64
     temperature  Humidity  moisture   N  K   P Fertilizer
0             26        52        38  37  0   0       Urea
1             29        52        45  12  0  36        DAP
2             34        65        62   7  9  30   14-35-14
3             32        62        34  22  0  20      28-28
4             28        54        46  35  0   0       Urea
..           ...       ...       ...  .. ..  ..        ...
149           26        52        46  23  0  19      28-28
150           29        58        49  12  0 

In [20]:
X = df_resampled.drop("Fertilizer", axis = 1)
Y = df_resampled["Fertilizer"]

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [21]:
from sklearn.ensemble import ExtraTreesClassifier

model = ExtraTreesClassifier(n_estimators = 100, random_state = 42)
model.fit(X_train, Y_train)

ExtraTreesClassifier(random_state=42)

In [22]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)
print(classification_report(Y_test, y_pred, zero_division = 0))

              precision    recall  f1-score   support

    10-26-26       1.00      1.00      1.00         4
    14-35-14       1.00      1.00      1.00         8
    17-17-17       1.00      1.00      1.00         3
       20-20       1.00      1.00      1.00         4
       28-28       1.00      1.00      1.00         5
         DAP       1.00      1.00      1.00         4
        Urea       1.00      1.00      1.00         3

    accuracy                           1.00        31
   macro avg       1.00      1.00      1.00        31
weighted avg       1.00      1.00      1.00        31



In [23]:
data['Fert_Predict'] = model.predict(fert_data.drop(columns = ["Fertilizer Name"]))
data

temperature  Humidity  moisture   N   K   P Fertilizer Name       SQI  \
0            26        52        38  37   0   0            Urea  0.149542   
1            29        52        45  12   0  36             DAP  0.193250   
2            34        65        62   7   9  30        14-35-14  0.740321   
3            32        62        34  22   0  20           28-28  0.466962   
4            28        54        46  35   0   0            Urea  0.290982   
..          ...       ...       ...  ..  ..  ..             ...       ...   
94           25        50        32  24   0  19           28-28  0.000000   
95           30        60        27   4  17  17        10-26-26  0.386129   
96           38        72        51  39   0   0            Urea  1.000000   
97           36        60        43  15   0  41             DAP  0.566999   
98           29        58        57  12   0  10           20-20  0.402177   

   Fert_Predict  
0          Urea  
1           DAP  
2      14-35-14  
3         28-28  
4          Urea  
..          ...  
94        28-28  
95     10-26-26  
96         Urea  
97          DAP  
98        20-20  

[99 rows x 9 columns]

In [24]:
import pickle

In [25]:
pickle_file = 'fertilizerPrediction.pkl'
with open(pickle_file, 'wb') as file:
    pickle.dump(model, file)